name: eeg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - einops==0.8.1
      - epilepsy2bids==0.0.7
      - filelock==3.16.1
      - fsspec==2024.12.0
      - jinja2==3.1.5
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.60.0
      - numpy==1.26.0
      - pandas==2.2.3
      - pillow==11.1.0
      - pyarrow==19.0.0
      - pyedflib==0.1.38
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - resampy==0.4.3
      - scipy==1.15.0
      - six==1.17.0
      - sympy==1.13.3
      - termcolor==2.5.0
      - timescoring==0.0.6
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - typing-extensions==4.12.2
      - tzdata==2024.2
